PLEX_URL   = "http://YOUR_PLEX_IP:32400"
PLEX_TOKEN = "YOUR_PLEX_TOKEN"
MUSIC_LIB  = "Music"

DB_PATH = "ridermusic.db"
SESSION_TIMEOUT_SECONDS = 75 * 60  # 75 min default

ADMIN_PASSWORD = "YOUR_ADMIN_PASSWORD"
ADMIN_SESSION_DAYS = 90
